server:
  address: localhost
  port: 8080
  tomcat:
    threads:
      max: 200 #default : 200
      min-spare: 10 #default : 10
    max-connections: 10000 #default : 10000
    accept-count: 100 #default : 100
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
