server:
  address: 0.0.0.0
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 10000
    accept-count: 100
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
