services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - z9-network
    ports:
      - ${PROMETHEUS_OUT_PORT}:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - z9-network
    ports:
      - ${GRAFANA_OUT_PORT}:3000
    environment:
      - TZ=Asia/Seoul
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always

  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    environment:
      - MYSQLD_EXPORTER_PASSWORD=${MYSQL_EXPORTER_PASSWORD}
    networks:
      - z9-network
    ports:
      - ${MYSQL_EXPORTER_OUT_PORT}:9104
    command:
      - "--mysqld.username=${MYSQL_EXPORTER_USERNAME}"
      - "--mysqld.address=${MYSQL_EXPORTER_ADDRESS}"
    restart: always

networks:
  z9-network:
    external: true

volumes:
  grafana-data:
