spring:
  application:
    name: backend
  config:
    additional-location: classpath:/config/
  profiles:
    group:
      dev: [ "dev_auth", "dev_db", "dev_web", "dev_server" ,"dev_docs" ]
      prod: [ "prod_auth", "prod_db", "prod_web", "prod_server", "prod_docs" ]
    active: dev