spring:
  application:
    name: backend
  config:
    import:
      - optional:classpath:config/${spring.profiles.active}/application-${spring.profiles.active}_db.yml
      - optional:classpath:config/${spring.profiles.active}/application-${spring.profiles.active}_server.yml
      - optional:classpath:config/${spring.profiles.active}/application-${spring.profiles.active}_auth.yml
      - optional:classpath:config/${spring.profiles.active}/application-${spring.profiles.active}_docs.yml
      - optional:classpath:config/${spring.profiles.active}/application-${spring.profiles.active}_web.yml
  profiles:
    group:
      dev: [ "dev_auth", "dev_db", "dev_web", "dev_server" ,"dev_docs" ]
      prod: [ "prod_auth", "prod_db", "prod_web", "prod_server", "prod_docs" ]
    active: dev